xendit/xendit-sdk-android

app/src/main/java/ch/itomy/xendit_example/AuthenticationActivity.java
app/src/main/java/ch/itomy/xendit_example/CreateTokenActivity.java
xendit-android/src/main/java/com/xendit/Models/XenditError.java
xendit-android/src/main/java/com/xendit/TokenBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/Xendit.java
xendit-android/src/main/java/com/xendit/XenditActivity.java
xendit-android/src/main/java/com/xendit/network/errors/NetworkError.java
xendit-android/src/main/res/values/strings.xml

Changelog:
Map backend error so it will have same error as xendit.js

map backend error

---

xendit-android/src/main/java/com/xendit/XenditActivity.java

Problem:
Malformed HTML causes blank screen on certain devices
Solution:
Update template to contain valid HTML

Fix 3ds authentication template html

---

.idea/markdown-navigator.xml
.idea/markdown-navigator/profiles_settings.xml
.idea/misc.xml
README.md
app/src/main/java/ch/itomy/xendit_example/AuthenticationActivity.java
app/src/main/java/ch/itomy/xendit_example/CreateTokenActivity.java
xendit-android/src/main/java/com/xendit/AuthenticationBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/AuthenticationCallback.java
xendit-android/src/main/java/com/xendit/Models/Token.java
xendit-android/src/main/java/com/xendit/Models/XenditError.java
xendit-android/src/main/java/com/xendit/TokenBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/Xendit.java
xendit-android/src/main/res/values/strings.xml

https://app.asana.com/0/247924003545825/380326752070833
https://app.asana.com/0/247924003545825/388449917507054

Pr tokenization improvements

---

app/src/main/java/ch/itomy/xendit_example/CreateTokenActivity.java
app/src/main/res/layout/activity_create_token.xml
xendit-android/src/main/java/com/xendit/Xendit.java

Changelogs:
Pass optional `should_authenticate` to backend to allow optional 3DS

add should authenticate

---

app/src/main/java/ch/itomy/xendit_example/CreateTokenActivity.java
xendit-android/src/main/java/com/xendit/Models/Authentication.java
xendit-android/src/main/java/com/xendit/Models/Token.java
xendit-android/src/main/java/com/xendit/Models/XenditError.java

Changelogs:
* Return authentication id if it's exists
* Map Flex's Validation error correctly

add authentication id; map flex VALDATION_ERROR

---

xendit-android/src/main/java/com/xendit/Models/Authentication.java

Problem:
No need to write authentication id in parcel
Solution:
Remove it

hotfix-parcel

---

app/build.gradle
xendit-android/src/main/java/com/xendit/TokenBroadcastReceiver.java

Problem:
App crashes when user clicks back button on 3ds webview
Solution:
Handle incomplete 3ds flow gracefully

Fix bug that causes app to crash when back button is pressed on 3ds view

---

.idea/misc.xml
xendit-android/src/main/java/com/xendit/XenditActivity.java

An error is expected onBackPressed but not onStop (which is called when the app is suspended)

Override onBackPressed, do not broadcast error on onStop

---

xendit-android/src/main/java/com/xendit/Models/XenditError.java

Changelogs:
Handle error if error response is null

handle null error response

---

app/src/main/java/com/xendit/example/ValidationUtilActivity.java
xendit-android/src/main/java/com/xendit/Xendit.java
xendit-android/src/main/java/com/xendit/utils/CardValidator.java
xendit-android/src/test/java/com/xendit/utils/CardValidatorTests.java

We are not validating CVN correctly based on card type. Will cause an error when creating charge, better to handle it before creating the token
Change the CVN validation logic to check card type

change cvn validation logic

---

app/src/main/java/com/xendit/example/CreateTokenActivity.java
xendit-android/src/main/java/com/xendit/Models/Authentication.java
xendit-android/src/main/java/com/xendit/Models/Token.java

We need to return `masked_card_number` during tokenization
Add the response in model and example

add masked card number to response

---

.idea/libraries/animated_vector_drawable_25_3_1.xml
.idea/libraries/appcompat_v7_25_3_1.xml
.idea/libraries/constraint_layout_1_0_1.xml
.idea/libraries/espresso_core_2_2_2.xml
.idea/libraries/espresso_idling_resource_2_2_2.xml
.idea/libraries/exposed_instrumentation_api_publish_0_5.xml
.idea/libraries/rules_0_5.xml
.idea/libraries/runner_0_5.xml
.idea/libraries/support_compat_25_3_1.xml
.idea/libraries/support_core_ui_25_3_1.xml
.idea/libraries/support_core_utils_25_3_1.xml
.idea/libraries/support_fragment_25_3_1.xml
.idea/libraries/support_media_compat_25_3_1.xml
.idea/libraries/support_v4_25_3_1.xml
.idea/libraries/support_vector_drawable_25_3_1.xml
.idea/libraries/volley_1_0_0.xml
.idea/misc.xml
.idea/modules.xml
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/utils/CardValidator.java
xendit-android/src/test/java/com/xendit/utils/CardValidatorTests.java

There are known issue that valid card number return invalid because it got invalid luhn validation
Try to change the logic and refer to known source:
- https://github.com/eix128/gnuc-credit-card-checker/blob/master/CCCheckerPro/src/com/gnuc/java/ccc/Luhn.java
- Tried with the cards with this issue and it passed the validation
- Tried with 2 personal cards and it passed the validation
Bump patch version

fix luhn validation

---

app/src/main/java/com/xendit/example/MainActivity.java
xendit-android/src/main/java/com/xendit/Xendit.java

implement xendit token

---

app/src/main/java/com/xendit/example/CreateTokenActivity.java
xendit-android/build.gradle
xendit-android/src/androidTest/java/com/xendit/TokenTest.java
xendit-android/src/main/java/com/xendit/Models/Authentication.java
xendit-android/src/main/java/com/xendit/Models/CardMetadata.java
xendit-android/src/main/java/com/xendit/Models/Token.java

[CC-3152] Added token metadata to 3DS and tokenization response

---

app/build.gradle
app/src/main/java/com/xendit/example/CreateTokenActivity.java
xendit-android/build.gradle
xendit-android/src/androidTest/java/com/xendit/AuthTest.java
xendit-android/src/androidTest/java/com/xendit/TokenTest.java
xendit-android/src/main/java/com/xendit/AuthenticatedTokenBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/AuthenticationCallback.java
xendit-android/src/main/java/com/xendit/Models/Address.java
xendit-android/src/main/java/com/xendit/Models/AuthenticatedToken.java
xendit-android/src/main/java/com/xendit/Models/Authentication.java
xendit-android/src/main/java/com/xendit/Models/BillingDetails.java
xendit-android/src/main/java/com/xendit/Models/CardMetadata.java
xendit-android/src/main/java/com/xendit/Models/Customer.java
xendit-android/src/main/java/com/xendit/Models/HasAuthenticationUrl.java
xendit-android/src/main/java/com/xendit/Models/Jwt.java
xendit-android/src/main/java/com/xendit/Models/Token.java
xendit-android/src/main/java/com/xendit/TokenBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/Xendit.java
xendit-android/src/main/java/com/xendit/XenditActivity.java

[CC-3186] Added support for EMV 3DS

---

xendit-android/build.gradle

Update version for these changes:
1. [CC-3447] Added card_info field to replace metadata https://github.com/xendit/xendit-sdk-android/pull/45
2. [CC-3562] 3DS EMV for frictionless card https://github.com/xendit/xendit-sdk-android/pull/46
[CC-3447]: https://xendit.atlassian.net/browse/CC-3447
[CC-3562]: https://xendit.atlassian.net/browse/CC-3562

update SDK version

---

xendit-android/src/main/java/com/xendit/Xendit.java

UAT https://xendit.atlassian.net/wiki/spaces/CA/pages/1217298502/UAT+Scenarios+-+EMV+3DS+Android+SDK

Added fallback to 3DS 1 flow

---

CHANGELOG.md
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Xendit.java

[CC-4070] Updated snowplow and add currency

---

app/build.gradle
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/XenditActivity.java

[CC-4180] Updated snowplow and added cardinal commerce credentials in example

---

.idea/gradle.xml
.idea/misc.xml
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Models/CardInfo.java

Add `fingerprint` information to `card_info` model.

add fingerprint to card info serialiazer

---

app/build.gradle
app/src/main/java/com/xendit/example/AuthenticationActivity.java
app/src/main/java/com/xendit/example/CreateTokenActivity.java
app/src/main/java/com/xendit/example/MainActivity.java
app/src/main/java/com/xendit/example/ValidationUtilActivity.java
gradle.properties
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Models/AuthenticatedToken.java
xendit-android/src/main/java/com/xendit/Models/ThreeDSRecommendation.java
xendit-android/src/main/java/com/xendit/utils/CardValidator.java

[CC-4318] AndroidX migration

---

app/build.gradle
app/src/main/java/com/xendit/example/AuthenticationActivity.java
app/src/main/java/com/xendit/example/CreateTokenActivity.java
app/src/main/java/com/xendit/example/models/AuthenticationResponse.java
app/src/main/java/com/xendit/example/models/TokenizationResponse.java
xendit-android/build.gradle
xendit-android/proguard-rules.pro

[CC-4320] Use consumer proguard

---

README.md
app/build.gradle
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Tracker/SnowplowTrackerBuilder.java
xendit-android/src/main/java/com/xendit/Xendit.java

Updated snowplow to version 2.x

---

README.md
app/build.gradle
app/src/main/java/com/xendit/example/AuthenticationActivity.java
app/src/main/java/com/xendit/example/CreateTokenActivity.java
app/src/main/res/layout/activity_authentication.xml
app/src/main/res/layout/activity_create_token.xml
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Tracker/SnowplowTrackerBuilder.java
xendit-android/src/main/java/com/xendit/Xendit.java

[CC-4807] Update snowplow and allow decimals for currency

---

xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Xendit.java

Call unregisterReceiver before registerReceiver.
Non breaking to current flow.

[CC-6753] Call unregisterReceiver before registerReceiver

---

xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Xendit.java

Add method `unregisterAllBroadcastReceiver`.
Non breaking to current flow.

[CC-6939] Add method unregisterAllBroadcastReceiver

---

app/src/main/res/values/strings.xml
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Xendit.java

https://xendit.atlassian.net/browse/CC-7552
- Added new method for re-tokenization

[CC-7552] add new method for retokenization

---

README.md
app/build.gradle
app/src/main/res/values/strings.xml
build.gradle
xendit-android/build.gradle

https://xendit.atlassian.net/browse/CC-7563
- Update cardinal sdk to `2.2.7-2`
- Update test card number
- Update `compileSdkVersion` & `targetSdkVersion`
- Remove `jcenter` & add `mavenCentral`

[CC-7563] Update cardinal sdk

---

CHANGELOG.md
README.md
xendit-android/build.gradle
xendit-android/src/main/AndroidManifest.xml
xendit-android/src/main/java/com/xendit/Xendit.java

- https://xendit.atlassian.net/browse/CC-8092
- Upgrade sentry-android to `6.15.0`
- Update sentry dsn
- Add tags to sentry event

[CC-8092] Update sentry-android

---

CHANGELOG.md
README.md
app/build.gradle
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/AuthenticatedTokenBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/AuthenticationBroadcastReceiver.java
xendit-android/src/main/java/com/xendit/TokenBroadcastReceiver.java

TLDR
https://xendit.slack.com/archives/CGY42DC3T/p1683080736501609?thread_ts=1682660203.684289&cid=CGY42DC3T

Handling external event msg

---

CHANGELOG.md
README.md
xendit-android/build.gradle

Dependencies list is not published to pom.xml, causing the sdk compiled classes corrupted

fix: package corruption

---

CHANGELOG.md
README.md
app/src/main/java/com/xendit/example/AuthenticationActivity.java
app/src/main/java/com/xendit/example/CreateTokenActivity.java
app/src/main/res/layout/activity_authentication.xml
app/src/main/res/layout/activity_create_token.xml
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/Xendit.java

- Allow mid_label to be passed for create token request
- Allow mid_label to be passed for unbundled create authentication request

add midLabel on create token and create authorization endpoint

---

README.md

- add midLabel parameter on token creation for createSingleUseToken, createMultipleUseToken, createAuthentication

Update readme.md to add midLabel on token creation

---

CHANGELOG.md
README.md
xendit-android/build.gradle
xendit-android/src/main/java/com/xendit/utils/CardValidator.java

From this [thread](https://xendit.slack.com/archives/C06L0DLT48Z/p1716431731182719)
- removed hardcoded dates
- Updated JCB detect func to same web FE

fix expirydate and jcb detection

---

.idea/gradle.xml
.idea/misc.xml
CHANGELOG.md
README.md
xendit-android/build.gradle

Update Sentry SDK to 8.16.0
